### ISSUE TITLE
Building up search queries

### ISSUE THREAD

**Issue by tbtommyb** [FAC9/hapi-places#73]
It would be really cool if it remembered previous choices so that you could get progressively more precise. So choose a cheap place and then click warmer so you get warm and cheap places. I think you could do this easily by appending the params to the existing URL?

**Comment by njsfield** [comment]
Awesome idea, we wanted to explore the option of narrowing down the result based on all previous results, but we found that the more specific the query- the more likely the nomad API would return null/errors. Instead of slowing down the app by creating new refined queries when the server returned null, we decided to not add this functionality and explore a more consistent API in the future
